# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.0-rc3"
zap = "red-blox/zap@0.6.28"
# rojo = "rojo-rbx/rojo@6.2.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
